### ISSUE TITLE
🚀 Feature: select Recruiter role

### ISSUE THREAD

**Issue by Matanga1-2** [galezra/lusha-register-extension#28]
# 🔖 Feature Description
It's not a feature, but it's also not a bug.
When filling out the segmentation quiz, we set the role as "Sales."
Instead, we should fill it as "Recruiter".

## 📝 Description
Recruiters have access to private emails, and after sign-up, this cannot be changed.
Instead, we should select "Recruiter" by default.

## ✌️ Implementation
Ideally, we can add to the config a "Role" option (and set the default to Recruiter).
In `src/utils/elements/segmentation-quiz-elements.ts` in `clickRole(role = Role.sales)` we can adjust to either -
1. Select by default `role.recruiting`.
2. Load the role from config.

## 🔄️ Additional Info
Recruiter gives access to private emails, and currently, when using auto-signup, we are missing this functionality.

**Comment by Matanga1-2** [comment]
I'd love to contribute to this issue

**Comment by galezra** [comment]
Let's proceed with the default role, 'recruiting.' The second option is indeed intriguing, but currently, we can't support it due to the absence of a segmentation quiz configuration. However, I believe it would be an excellent addition to consider as a future feature request for implementing a segmentation quiz page configuration. 
 I've assigned this issue to you 🚀

**Comment by Matanga1-2** [comment]
This is a status solution. we need to open a new request to have a dynamic solution
